### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Tooconfident** [nosthas/prj-rev-bwfs-tea-cozy#4]
Grade: Meets Expectations

Good job with this project. I really didn't have any major criticism or preferences on changing your decisions. I really liked your choices and you show a solid knowledge of flex and other complex css properties like z-index. You will see my line issue's are more commentary on alternative solutions to your style choices. Whether you think they are better or helpful is up to you. I hope you find them nice options to clean things up and make it DRY(Don't Repeat Yourself). Start looking into media queries for responsive design websites. You are totally ready for making your website mobile friendly and getting a head start on that will help you going forward. Great work!

https://css-tricks.com/snippets/css/media-queries-for-standard-devices/

**Comment by nosthas** [comment]
Thanks for your review. Definitely very helpful tips. Trying to put all together for the next projects.
Regarding media queries what would be the recommended way to write them in the css file? A separate and new media query for each css rules that need specific treatment in other devices/resolutions or a media query containing all css rules that are targeting that specific device/resolution? I've seen both but not sure what would be the best approach.
